### PR TITLE
issue#20 Webhook parsing

### LINKED ISSUE #20: Webhook parsing
Webhooks are POST requests containing JSON. Parse this JSON into a developer-friendly and documented data format so it can be used by the server and further down the pipeline. See SPEC.md "GitHub Event Validation" for more details.

### PR DESCRIPTION
**Pull request by Lindefor**
feat: webhook parsing class which automatically parses important information from the webhook payload

### CODE REVIEW

**Comment by Lindefor** [comment]
I've spent 30min trying to find an example payload in the GitHub docs but cannot find any. Hence, I've not implemented a test for the class. We could perhaps implement it at a later stage when we've received examples?

**Review by Tobiky — COMMENTED** [review]
I found the documentation for the `pull_request` payload type [here](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=assigned#pull_request), there are some more links there for more detailed and related information as well. Do you think that this will be enough to create tests?

**Comment by Lindefor** [comment]
Saw that one as well, but it does not contain any example payload as far as I can see.

**Review by Tobiky — APPROVED** [review]
Awesome job, good work! Feel free to merge

**Pull request merged**
