### PR TITLE
Issue #11 CI#3 status notification

### LINKED ISSUE #14: Set up for Github API Usage
The Github API will inevitably require tokens, access, or other administrative means to be usable for, notably, #11 . Set up the different means and requirements for this to function. Update this issue with more information after completing #2 and/or #1 .

### PR DESCRIPTION
**Pull request by Lindefor**
Not sure if this completely closes the issue, seeing as this is only a working implementation of status notification through the GitHub API. But most of the requirements in the issue should be fulfilled. The only missing part is actually linking it to the test results, however that must wait until #10 is completed.

The tests have been run and has passed on the ssh server.

### CODE REVIEW

**Review by Tobiky — COMMENTED** [review]
LGTM, I'll put down another review when we have the build log URLs up and running

**Comment by Lindefor** [comment]
Should that be part of this PR? A bit large of a PR if it also includes a HTML hosting of test results. Will also include syntax results so I was thinking we might add it as another issue, since the syntax solution has yet to be implemented. What do you think?

**Comment by Tobiky** [comment]
> Should that be part of this PR? A bit large of a PR if it also includes a HTML hosting of test results. Will also include syntax results so I was thinking we might add it as another issue, since the syntax solution has yet to be implemented. What do you think?

We can do both ways. Having large PR's are fine. We can also look from the perspective of closing the feature as complete despite it being incomplete. Can resolve the latter in two ways; make a new smaller issue for parts of the features, create a branch based on this one, and lastly merge to resolve that issue. Or we can wait for the other functionalities to be implemented to merge into this branch. Lastly is ignoring the completeness of the issue.

From your dev perspective, what do you think the best course of action is?

**Comment by Lindefor** [comment]
I see your point. My only concern is that the HTML contents would only include the testing, not the syntax. However, it would be reasonable to add as part of this issue, and then add the syntax results later. I prefer this to merging with other branches 👍

**Comment by Tobiky** [comment]
> I see your point. My only concern is that the HTML contents would only include the testing, not the syntax. However, it would be reasonable to add as part of this issue, and then add the syntax results later. I prefer this to merging with other branches 👍

Reasonable compromise, lets do that!

**Comment by Lindefor** [comment]
Added the target_url functionality. Will test how well it works in #10

**Review by Tobiky — APPROVED** [review]
Sweet, that might be enough in that case and issue any problems as a bug when it appears. If so, feel free to merge. Thoughts?

**Comment by Lindefor** [comment]
Sounds great!

**Pull request merged**
